In [1]:
import numpy as np

In [10]:
R = np.ones((10,2,2))
x = np.ones((10, 2, 1))


In [12]:
(np.ones((2,2)) @ np.ones((2,1))).shape

(2, 1)

In [16]:
t = np.einsum("ijk, ijl -> ijl", R, x)
t.shape

array([[9., 9., 9., 9., 9., 9.],
       [9., 9., 9., 9., 9., 9.],
       [9., 9., 9., 9., 9., 9.],
       [9., 9., 9., 9., 9., 9.],
       [9., 9., 9., 9., 9., 9.],
       [9., 9., 9., 9., 9., 9.]])

In [22]:
H = np.ones((10,3,6))
P = np.ones((10, 3, 3))

b = H.transpose(0,2, 1)@P@H

In [23]:
b.shape

(10, 6, 6)

In [60]:
a = np.ones(((10, 3, 1)))
a = np.zeros((10,3,1))
a[:] = np.array([[1],[2],[3]])
b = np.ones((10, 3, 3))*2

# val = np.einsum('kil,kij', a, b)
val = np.einsum('kil,kij,kji->k', a, b, a)
val

array([72., 72., 72., 72., 72., 72., 72., 72., 72., 72.])

In [59]:
A = np.array([[1],[2],[3]])
B = np.ones((3,3))*2
A.T@B@A

array([[72.]])

In [48]:
A.T@B@A

array([[9.]])